org: helmer
app: nestjs-lambda-dynamo-serverless
service: nestjs-lambda-dynamo-serverless
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

# custom:
#   tableName: 'nest-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs16.x
  # iam:
  #   role:
  #     statements:
  #       - Effect: Allow
  #         Action:
  #           - dynamodb:Query
  #           - dynamodb:Scan
  #           - dynamodb:GetItem
  #           - dynamodb:PutItem
  #           - dynamodb:UpdateItem
  #           - dynamodb:DeleteItem
  #         Resource:
  #           - Fn::GetAtt: [ NestJsTable, Arn ]
  # environment:
  #   USERS_TABLE: ${self:custom.tableName}

functions:
  index:
    handler: src/main.handler
    events:
      - httpApi:
          method: GET
          path: /
  create:
    handler: src/main.handlerPost
    events:
      - httpApi:
          method: POST
          path: /

# resources:
#   Resources:
#     NestJsTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         AttributeDefinitions:
#           - AttributeName: email
#             AttributeType: S
#         KeySchema:
#           - AttributeName: email
#             KeyType: HASH
#         BillingMode: PAY_PER_REQUEST
#         TableName: ${self:custom.tableName}
